# hash-identificacao: 97298dad08457b8545d4cb3fb07b150f4f754aa559b2d57d00ec65d28fed16ea

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# Formata o JSON das respostas com indenta��o
spring.jackson.serialization.INDENT_OUTPUT=true
